version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: inventory-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - inventory-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: inventory-backend
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: development
      MONGODB_URI: mongodb://admin:password@mongodb:27017/inventory?authSource=admin
    depends_on:
      - mongodb
    networks:
      - inventory-network
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: inventory-frontend
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:5000
    depends_on:
      - backend
    networks:
      - inventory-network
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next

volumes:
  mongo-data:

networks:
  inventory-network:
    driver: bridge